# Generated by Django 5.1.1 on 2024-09-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
