# Generated by Django 5.1 on 2024-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
